version: "3.8"

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    command: npm run start

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 777fabri777
      POSTGRES_DB: nestjs
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
